title:               Кирдан
url:                 kkirdan.github.io
baseurl:             ''
permalink:           /blog/:title:output_ext

vk:                  https://vk.com/kirdan
telegram:            https://t.me/k_kirdan
email:               latif.rosh@gmail.com
patreon:             https://www.patreon.com/user?u=120067868
boosty:              https://boosty.to/k_kirdan

future: true

google_analytics: G-BQPMQ2SPK5
