# МОДИФИЦИРОВАНО

# Setup
title:               Кирдан
url:                 kkirdan.github.io
baseurl:             ''
permalink:           /blog/:title:output_ext

vk:                  https://vk.com/kirdan
telegram:            https://t.me/k_kirdan
email:               latif.rosh@gmail.com

future: true

# Custom vars
google_analytics: G-BQPMQ2SPK5