title:               Кирдан
url:                 kkirdan.github.io
baseurl:             ''
permalink:           /blog/:title:output_ext

vk:                  https://vk.com/kirdan
contact_vk:          https://vk.com/latif_rosh
telegram:            https://t.me/k_kirdan
contact_telegram:    https://t.me/KKirdan
email:               latif.rosh@gmail.com

future: true

google_analytics: G-BQPMQ2SPK5
